[package]
name = "rcc_driver"
version.workspace = true
edition.workspace = true

[dependencies]
rcc_codegen  = { workspace = true }
rcc_interner = { workspace = true }
rcc_lexer    = { workspace = true }
rcc_parser   = { workspace = true }

clap = { workspace = true }
