[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
rcc_lexer = { path = "./crates/rcc_lexer/" }

clap = { version = "4.5.17", features = ["derive"] }
