[package]
name = "rcc_arena"
version.workspace = true
edition.workspace = true

[dependencies]
allocator-api2 = { workspace = true }
bumpalo        = { workspace = true, features = ["allocator-api2"] }
