[package]
name = "rcc_ast"
version.workspace = true
edition.workspace = true

[dependencies]
rcc_arena    = { workspace = true }
rcc_interner = { workspace = true }
rcc_span     = { workspace = true }
